### ISSUE TITLE
deisgn issue

### ISSUE THREAD

**Issue by razibchamp** [razibchamp/FundArising-#13]
should we maintain the same design like blog.html on every page ?
like blog.html has a title so when we are on a page the title can be shown there and menu under the title.

**Comment by SabiqueShadmanRafeed** [comment]
we can use this design. It would be more user friendly I guess and it would look similar to how a website looks

**Comment by razibchamp** [comment]
as of now it will be easy to navigate since we have some limitation over technologies but there is not valid guidance regarding how a website should look. different website looks different. 

**# I am applying the design on other pages.**
